name: wp
description: Set video wallpaper for desktop.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dart_vlc: 0.3.0
  file_selector: 0.8.4+3
  get_storage: 2.0.3
  hotkey_manager: 0.1.7
  launch_at_startup: 0.1.7
  system_tray: 0.1.1
  win32: 2.6.1
  window_manager: 0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
